// "use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DarkModeProvider } from "../components/DarkModeContext";

import { Providers } from "./providers";

// src/app/page.tsx
export const metadata = {
  title: "SkillSwap - Home",
  description: "Find and swap skills with others.",
  icons: {
    icon: "/favicon.ico",
    logo: "/globe.svg",
  },
};

// ...your page code (remove "use client")


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en" className="dark">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Providers>
					<DarkModeProvider>{children}</DarkModeProvider>
				</Providers>
			</body>
		</html>
	);
}
